name: Update GitIgnore

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  update-gitignore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update GitIgnore and Untrack Files
        run: |
          git rm --cached -r .
          git add .
          git commit -m "Apply .gitignore" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
